# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: README

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1

    - name: 'Build & Test'
      run: |
        # Build the project, with its main file included, without unittests
        dub build --compiler=$DC
        # Build and run tests, as defined by `unittest` configuration
        # In this mode, `mainSourceFile` is excluded and `version (unittest)` are included
        # See https://dub.pm/package-format-json.html#configurations
        dub test --compiler=$DC

    - name: 'Test README'
      run: |
        # Build the project, with its main file included, without unittests
        dub run md --compiler=$DC -- README.md
        dub run md --compiler=$DC -- README.ja.md

    - name: 'Test Examples with options'
      run: |
        # Build the project, with its main file included, without unittests
        dub run md --compiler=$DC -- examples/test-build.md --build=release
        dub run md --compiler=$DC -- examples/test-compiler.md --compiler=$DC
        dub run md --compiler=$DC -- examples/test-build.md --build=release --compiler=$DC
        dub run md --compiler=$DC -- examples/test-compiler.md --build=release --compiler=$DC

    - name: 'Run filter tests'
      run: dub run md -- examples/test-filter.md --filter test1
    - name: 'Run multiple filters tests'
      run: dub run md -- examples/test-filter-multiple.md --filter test1 --filter test2
    - name: 'Run no matching filter tests'
      run: dub run md -- examples/test-filter-multiple.md --filter test100
